### ISSUE TITLE
trademe not working 1.20.6

### ISSUE THREAD

**Issue by WhiteProject1** [Zrips/TradeMe#22]
[11:57:44] [Server thread/ERROR]: Error occurred while enabling TradeMe v6.2.1.4 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getItemMeta()" because the return value of "net.Zrips.CMILib.Items.CMIItemStack.getItemStack()" is null
	at CMILib1.4.7.8.jar/net.Zrips.CMILib.Items.CMIItemSerializer.getItem(CMIItemSerializer.java:401) ~[CMILib1.4.7.8.jar:?]
	at CMILib1.4.7.8.jar/net.Zrips.CMILib.Items.CMIItemSerializer.deserialize(CMIItemSerializer.java:511) ~[CMILib1.4.7.8.jar:?]
	at CMILib1.4.7.8.jar/net.Zrips.CMILib.Items.CMIItemStack.deserialize(CMIItemStack.java:865) ~[CMILib1.4.7.8.jar:?]
	at TradeMe-6.2.1.4.jar/me.Zrips.TradeMe.ConfigFile.getItem(ConfigFile.java:760) ~[TradeMe-6.2.1.4.jar:?]
	at TradeMe-6.2.1.4.jar/me.Zrips.TradeMe.ConfigFile.LoadConfig(ConfigFile.java:733) ~[TradeMe-6.2.1.4.jar:?]
	at TradeMe-6.2.1.4.jar/me.Zrips.TradeMe.ConfigFile.reload(ConfigFile.java:784) ~[TradeMe-6.2.1.4.jar:?]
	at TradeMe-6.2.1.4.jar/me.Zrips.TradeMe.TradeMe.onEnable(TradeMe.java:291) ~[TradeMe-6.2.1.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:git-Paper-72]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:git-Paper-72]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:609) ~[paper-1.20.6.jar:git-Paper-72]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:558) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:681) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-72]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[11:57:44] [Server thread/INFO]: [TradeMe] Disabling TradeMe v6.2.1.4
[11:57:44] [Server thread/ERROR]: Error occurred while disabling TradeMe v6.2.1.4
java.lang.NullPointerException: Cannot read field "TradeMap" because the return value of "me.Zrips.TradeMe.TradeMe.getUtil()" is null
	at TradeMe-6.2.1.4.jar/me.Zrips.TradeMe.TradeMe.onDisable(TradeMe.java:545) ~[TradeMe-6.2.1.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.20.6.jar:git-Paper-72]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.20.6.jar:git-Paper-72]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:549) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.20.6.jar:git-Paper-72]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:git-Paper-72]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:609) ~[paper-1.20.6.jar:git-Paper-72]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:558) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:681) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-72]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]

**Comment by ScrapMetalGolem** [comment]
Same result (as expected) for Purpur:

[08:36:49] [Server thread/INFO]: [TradeMe] Enabling TradeMe v6.2.1.4
[08:36:49] [Server thread/INFO]: [TradeMe] Version 6.2.1.4 has been enabled
[08:36:49] [Server thread/INFO]: [TradeMe] Vault plugin was found!
[08:36:49] [Server thread/INFO]: [TradeMe] Jobs plugin was found!
[08:36:49] [Server thread/INFO]: [TradeMe] JobsPoints feature enabled!
[08:36:49] [Server thread/ERROR]: Error occurred while enabling TradeMe v6.2.1.4 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getItemMeta()" because the return value of "net.Zrips.CMILib.Items.CMIItemStack.getItemStack()" is null
	at CMILib1.4.7.8.jar/net.Zrips.CMILib.Items.CMIItemSerializer.getItem(CMIItemSerializer.java:401) ~[CMILib1.4.7.8.jar:?]
	at CMILib1.4.7.8.jar/net.Zrips.CMILib.Items.CMIItemSerializer.deserialize(CMIItemSerializer.java:511) ~[CMILib1.4.7.8.jar:?]
	at CMILib1.4.7.8.jar/net.Zrips.CMILib.Items.CMIItemStack.deserialize(CMIItemStack.java:865) ~[CMILib1.4.7.8.jar:?]
	at TradeMe6.2.1.4.jar/me.Zrips.TradeMe.ConfigFile.getItem(ConfigFile.java:760) ~[TradeMe6.2.1.4.jar:?]
	at TradeMe6.2.1.4.jar/me.Zrips.TradeMe.ConfigFile.LoadConfig(ConfigFile.java:733) ~[TradeMe6.2.1.4.jar:?]
	at TradeMe6.2.1.4.jar/me.Zrips.TradeMe.ConfigFile.reload(ConfigFile.java:784) ~[TradeMe6.2.1.4.jar:?]
	at TradeMe6.2.1.4.jar/me.Zrips.TradeMe.TradeMe.onEnable(TradeMe.java:291) ~[TradeMe6.2.1.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.20.6.jar:git-Purpur-2200]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.6.jar:git-Purpur-2200]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:623) ~[purpur-1.20.6.jar:git-Purpur-2200]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:572) ~[purpur-1.20.6.jar:git-Purpur-2200]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:684) ~[purpur-1.20.6.jar:git-Purpur-2200]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:443) ~[purpur-1.20.6.jar:git-Purpur-2200]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:357) ~[purpur-1.20.6.jar:git-Purpur-2200]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[purpur-1.20.6.jar:git-Purpur-2200]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[purpur-1.20.6.jar:git-Purpur-2200]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[08:36:49] [Server thread/INFO]: [TradeMe] Disabling TradeMe v6.2.1.4
[08:36:49] [Server thread/ERROR]: Error occurred while disabling TradeMe v6.2.1.4
java.lang.NullPointerException: Cannot read field "TradeMap" because the return value of "me.Zrips.TradeMe.TradeMe.getUtil()" is null
	at TradeMe6.2.1.4.jar/me.Zrips.TradeMe.TradeMe.onDisable(TradeMe.java:545) ~[TradeMe6.2.1.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[purpur-1.20.6.jar:git-Purpur-2200]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[purpur-1.20.6.jar:git-Purpur-2200]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:549) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[purpur-1.20.6.jar:git-Purpur-2200]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.6.jar:git-Purpur-2200]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:623) ~[purpur-1.20.6.jar:git-Purpur-2200]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:572) ~[purpur-1.20.6.jar:git-Purpur-2200]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:684) ~[purpur-1.20.6.jar:git-Purpur-2200]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:443) ~[purpur-1.20.6.jar:git-Purpur-2200]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:357) ~[purpur-1.20.6.jar:git-Purpur-2200]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[purpur-1.20.6.jar:git-Purpur-2200]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[purpur-1.20.6.jar:git-Purpur-2200]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Zrips** [comment]
Should be resolved with next CMILib update
