### ISSUE TITLE
Error with MyPets plugin

### ISSUE THREAD

**Issue by dimon0230ru** [Zrips/TradeMe#3]
Caused by: java.lang.NoSuchMethodError: de.Keyle.MyPet.api.entity.MyPet.getSkilltree()Lde/Keyle/MyPet/api/skill/skilltree/SkillTree; at me.Zrips.TradeMe.SpecialActionPack.MyPetUtil.Buttons(MyPetUtil.java:164) ~[?:?] at me.Zrips.TradeMe.Util.updateAmountOffer(Util.java:1002) ~[?:?] at me.Zrips.TradeMe.commands.list.accept.perform(accept.java:81) ~[?:?] at me.Zrips.TradeMe.commands.CommandsHandler.onCommand(CommandsHandler.java:195) ~[?:?] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-29]

**Comment by dimon0230ru** [comment]
MyPet-3.11-SNAPSHOT-B1588

**Comment by Zrips** [comment]
Should be fixed with next build
