### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by bobhenl** [Zrips/TradeMe#4]
```
[18:12:17] [Server thread/ERROR]: [TradeMe] Task #1363506 for TradeMe v6.0.5.3 generated an exception
[18:12:17] [Server thread/ERROR]: [TradeMe] Suspected Plugins: 
[18:12:17] [Server thread/ERROR]: [TradeMe] 	TradeMe{enabled,ver=6.0.5.3,path=plugins/TradeMe6.0.5.3.jar}
[18:12:17] [Server thread/ERROR]: [TradeMe] Exception details below: 
java.util.NoSuchElementException: No value present
	at java.util.OptionalLong.getAsLong(OptionalLong.java:118) ~[?:1.8.0_171]
	at me.Zrips.TradeMe.SpecialActionPack.TokenManagerUtil.isLegit(TokenManagerUtil.java:227) ~[?:?]
	at me.Zrips.TradeMe.Util.checkTradeLegit(Util.java:724) ~[?:?]
	at me.Zrips.TradeMe.Counter.counter(Counter.java:72) ~[?:?]
	at me.Zrips.TradeMe.Counter$1.run(Counter.java:156) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-25]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:469) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-25]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1386) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-25]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:398) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-25]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1295) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-25]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1016) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-25]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:176) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-25]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by Zrips** [comment]
Gets a fix with next version.
